import json
from pathlib import Path
from ortools.sat.python import cp_model
from math import prod
from itertools import product

def combos(n, op, target, k):
    out = []
    for v in product(range(1, n + 1), repeat=k):
        if k == 1: ok = v[0] == target
        elif op == '+': ok = sum(v) == target
        elif op == '*': ok = prod(v) == target
        elif op == '-': ok = k == 2 and abs(v[0] - v[1]) == target
        elif op == '/': ok = k == 2 and (max(v) == target * min(v))
        else: ok = False
        if ok:
            out.append(v)
    return out

def solve(n, cages):
    if n < 1:
        raise ValueError(f'Grid size must be positive, got {n}.')
    m = cp_model.CpModel()
    x = {(r, c): m.NewIntVar(1, n, f'x_{r}_{c}') for r in range(n) for c in range(n)}
    for i in range(n):
        m.AddAllDifferent([x[(i,c)] for c in range(n)])
        m.AddAllDifferent([x[(r,i)] for r in range(n)])

    for target, op, cells in cages:
        cells = [tuple(cell) for cell in cells]
        if not cells:
            raise ValueError(f'Cage {target}{op} has no cells.')
        if any(len(cell) != 2 or not (0 <= cell[0] < n and 0 <= cell[1] < n) for cell in cells):
            raise ValueError(f'Cage {target}{op} contains a cell outside a {n}x{n} board: {cells}.')
        allowed = combos(n, op, target, len(cells))
        if not allowed:
            raise ValueError(f'Cage {target}{op} has no valid combinations for {len(cells)} cells.')
        m.AddAllowedAssignments([x[c] for c in cells], allowed)

    solver = cp_model.CpSolver()
    status = solver.Solve(m)
    if status == cp_model.OPTIMAL or status == cp_model.FEASIBLE:
        return [[solver.Value(x[(r, c)]) for c in range(n)] for r in range(n)]
    if status == cp_model.INFEASIBLE:
        raise ValueError('The detected KenKen has no solution. Check the detected cages and glyphs.')
    raise RuntimeError(f'CP-SAT failed with status {solver.StatusName(status)}.')


def load_detected_json(path):
    """Load the JSON generated by vision.export_json."""
    path = Path(path)
    try:
        data = json.loads(path.read_text(encoding='utf-8'))
    except OSError as exc:
        raise OSError(f'Could not read detected puzzle JSON: {path}') from exc
    except json.JSONDecodeError as exc:
        raise ValueError(f'Invalid detected puzzle JSON: {path}') from exc

    n = data.get('n')
    images = data.get('images')
    if not isinstance(n, int) or n < 1 or not isinstance(images, list):
        raise ValueError("Detected JSON must contain a positive integer 'n' and an 'images' list.")
    return data


def detected_cages(image):
    """Convert one exported image entry to the tuple format accepted by solve."""
    cages = image.get('cages')
    if not isinstance(cages, list):
        raise ValueError(f"Image entry {image.get('filename', '<unnamed>')} has no valid 'cages' list.")
    result = []
    for index, cage in enumerate(cages):
        if not isinstance(cage, dict):
            raise ValueError(f'Cage {index} is not an object.')
        missing = {'target', 'op', 'cells'} - cage.keys()
        if missing:
            raise ValueError(f"Cage {index} is missing fields: {sorted(missing)}.")
        op = cage['op']
        if op not in {'=', '+', '-', '*', '/'}:
            raise ValueError(f"Cage {index} has unsupported operator {op!r}.")
        result.append((int(cage['target']), op, cage['cells']))
    return result


def solve_detected_json(path, filename=None):
    """Solve one exported board and return its name, detected cages and solution."""
    data = load_detected_json(path)
    images = data['images']
    if filename is not None:
        images = [image for image in images if image.get('filename') == filename]
        if not images:
            raise ValueError(f'No image named {filename!r} was found in {path}.')
    if len(images) != 1:
        raise ValueError('The JSON contains multiple boards; pass filename= to select one.')
    image = images[0]
    cages = detected_cages(image)
    solution = solve(data['n'], cages)
    return {'n': data['n'], 'filename': image.get('filename'), 'cages': cages, 'solution': solution}


def solve_detected_file(path, output=None):
    """Solve every board in an exported JSON and optionally save the solutions."""
    data = load_detected_json(path)
    solved = []
    for image in data['images']:
        solved.append({
            'filename': image.get('filename'),
            'solution': solve(data['n'], detected_cages(image)),
        })
    result = {'n': data['n'], 'boards': solved}
    if output is not None:
        Path(output).write_text(json.dumps(result, indent=2), encoding='utf-8')
    return result


if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(description='Solve KenKen boards exported by the vision notebook.')
    parser.add_argument('detected_json', help='Path to pred.json generated by export_json')
    parser.add_argument('-o', '--output', help='Optional path for the solutions JSON')
    parser.add_argument('--filename', help='Solve only this filename when the input has multiple boards')
    args = parser.parse_args()

    if args.filename:
        result = solve_detected_json(args.detected_json, args.filename)
    else:
        result = solve_detected_file(args.detected_json, args.output)
    if args.output is None or args.filename:
        print(json.dumps(result, indent=2))